### ISSUE TITLE
Project packaging suggestion

### ISSUE THREAD

**Issue by Eddiedude1** [jmhcodes/youtube#1]
To make your project reproducible by others it's a good idea to work in a virtual environment and saving it's configuration.  This is important also for the software dev lifecycle.  Dev --> Testing --> Deployment.  Each stage should be almost an exact copy of your development version that you are pushing to test then later to deployment. 

A virtual environment is an environment that is specific for your project.  It can be activated and deactivated and contains only the necessary packages needed for the project when activated.  It's okay to have a virtual environment specific to every project.  

The requirements can be contained in a requirements.txt or a envrionment.yml file. 

This is how you would do it with python's virtual environment management in a bash terminal:
### Go to project directory
$ cd your/project/root/dir

### Create virtual environment
$ python3 -m venv {name-of-venv}
* This will create a directory called {name-of-env} in your root directory
* **Add this directory to your .gitignore file so it does not get tracked by git and you don't push it to version control**

### Activate virtual environment
$ . {name-of-venv}/bin/activate
* This activated virtual environment will only contain pip and setuptools  packages
* You then go and add the packages you need and update it 

### Install packages
* It's customary to have to add packages as your project matures and/or when implementing additional features
* Make sure to update your configuration file (requirements.txt (python) or environment.yml (conda)) an push your updates
* Check out the conda documentation on virtual environments if you prefer to used Conda.  These instructions are based on python's native venv manager

In this example below I have created a virtual environment inside of the **project_test** directory called **py-projecttest**.
```$ pwd
/Users/guillermogonzalez/projects/project_test
$ ls
$ python3 -m venv py-projecttest
$ ls
py-projecttest/
$ . py-projecttest/bin/activate
(py-projecttest) $ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip .(9.0.1)
setuptools (28.8.0)
You are using pip version 9.0.1, however version 20.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command
```
One way to save the collection of packages is with this command: 
```
$ pip3 freeze > requirements.txt
```

When another person wants to duplicate your work they can first clone the rope into there dev environment then run: 

1. Create a virtual environment
2. Install from requirements.txt:
```
$ pip3 install -r requirements.txt
```

**Comment by jmhcodes** [comment]
Thank you for this suggestion @Eddiedude1, cookie cutter is a sweet tool and I really like the organization it provides. 

Another cool thing you can do is make html references within your file directory [using tree -H > file_tree.html](https://www.cyberciti.biz/faq/linux-show-directory-structure-command-line/). 

The [README](https://github.com/jmhcodes/youtube/blob/master/README.md) for this repo is a good example of what it looks like. I will admit, adding the descriptions to each directory did take some time, but that probably could be simplified with some html padding. 

Nonetheless thank you for your thorough suggestion. The repo was updated and bettered by your input!
